### ISSUE TITLE
Source version (or update policy)

### ISSUE THREAD

**Issue by rgiannico** [biothings/myvariant.py#10]
Hello, 
Is there some way to get the source release versions we are querying from? 

For example the Cosmic database has more or less 4 new releases a year : https://cancer.sanger.ac.uk/cosmic/release_notes/
What's your update policy? Do you always query from the latest online version of each Source or you have an internal database?
If you use an internal database how often do you update the info from each source? Once a month? Once a year? 

It will be very useful to have a "source version" field or a "last update on <date>" field ! 

Thank you :)

**Comment by kevinxin90** [comment]
Hi @rgiannico 
We document all the metadata information regarding MyVariant.info, e.g update policy, licence info here: http://myvariant.info/v1/metadata.

For the specific datasource "cosmic", as mentioned in the metadata, 

> COSMIC v68 was imported from UCSC database dump. This is the last freely available somatic variants from COSMIC before their licence change.

Thanks!

**Comment by rgiannico** [comment]
Great! Thank you so much, that was exactly the info I was searching for :)
