### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by MBeyens** [biothings/myvariant.py#4]
Dear

I'm using the python API, and until today it worked great! I'm getting 500 server errors, for some variants that worked previous analyses. eg. chr16:g.28883241A>G works but chr1:g.11167508A>T fails.

Are there any server connection issues?

Thank you in advance

Matthias

**Comment by kevinxin90** [comment]
Hi Mathhias,

Are you sure this 'chr1:g.11167508A>T' works before? We haven't done any data update on MyVariant.info this week. And I have checked our database history for the past 3 months. This variant never appears in our hg19 database before.

One thing I would suggest checking is we offer variant annotation using either hg19 or h38 genome assembly. MyVariant.info API uses hg19 assembly by default. For example, http://myvariant.info/v1/variant/chr16:g.28883241A>G will by default look for the variant on hg19 assembly. 

For your variant 'chr1:g.11167508A>T', http://myvariant.info/v1/variant/chr1:g.11167508A>T returns 500 error, which means there is no annotation information on hg19 assembly. But it you try http://myvariant.info/v1/variant/chr1:g.11167508A>T?assembly=hg38. This will help you find all annotations for this variant on hg38 assembly. And there is actually one hit for this variant on hg38. 

Thus, I think for the two variant you provided, they are actually using different reference genome assembly. 'chr16:g.28883241A>G' is actually on hg19 assembly, while 'chr1:g.11167508A>T' is on hg38 assembly. Could you double check for that?

Thanks!
Kevin
