### ISSUE TITLE
500 server Error: internal Error for url:http://myvariant.onfo/vl/variant/

### ISSUE THREAD

**Issue by avellab** [biothings/myvariant.py#9]
I am getting the following error when running my script, I had no issue with this before when running my script previously.

File "/home/clia/Clia_env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url:     http://myvariant.info/v1/variant/

**Comment by kevinxin90** [comment]
Hi @avellab, our developed @namespacestd0 has optimized our AWS instances to eliminate the issue that occurred to you. Feel free to try it out.
